const APPWRITE_ENDPOINT = process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT;
const APPWRITE_PROJECT_ID= process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID;

export const conf = {
    APPWRITE_ENDPOINT,
    APPWRITE_PROJECT_ID
}